"""Added paystack reference to purchase model

Revision ID: a02e715a2ec3
Revises: d3cc4b1383bf
Create Date: 2026-07-10 18:30:36.452537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02e715a2ec3'
down_revision = 'd3cc4b1383bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_reference', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('uq_purchase_paystack_reference', ['paystack_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint('uq_purchase_paystack_reference', type_='unique')
        batch_op.drop_column('paystack_reference')

    # ### end Alembic commands ###
