"""add purchase model

Revision ID: d3cc4b1383bf
Revises: 
Create Date: 2026-07-08 10:51:23.479666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cc4b1383bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('unique_video_payment', ['video_id', 'student_id'])
        batch_op.create_foreign_key('fk_purchase_video', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_video', type_='foreignkey')        
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
